repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
      - id: alejandra-system
  - repo: https://github.com/cmhughes/latexindent.pl
    rev: V3.19.1
    hooks:
      - id: latexindent
  - repo: local
    hooks:
      - id: chktex
        name: chktex
        entry: chktex
        language: system
        types: [tex]
