repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
      - id: alejandra-system
  - repo: https://github.com/cmhughes/latexindent.pl
    rev: V3.23.9
    hooks:
      - id: latexindent
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.2
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
  - repo: local
    hooks:
      - id: chktex
        name: chktex
        entry: chktex
        language: system
        types: [tex]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
